name: Python Setup, Poetry, and Testing

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  setup-poetry-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python v${{inputs.version}}
      uses: actions/setup-python@v4
      with:
        python-version: ${{inputs.version}}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Run tests
      run: poetry run pytest -v -s
